
export const SIGN_IN = 'SIGN_IN';
export const SIGN_UP = 'SIGN_UP';


export const SET_HEIGHT = 'SET_HEIGHT';
export const SET_NUM_COLUMNS = 'SET_NUM_COLUMNS';

export const OPEN_CHAT_WINDOW = "OPEN_CHAT_WINDOW";
export const CLOSE_CHAT_WINDOW = "CLOSE_CHAT_WINDOW";
export const SEND_CHAT_MESSAGE = "SEND_CHAT_MESSAGE";
export const RECEIVE_CHAT_MESSAGE = "RECEIVE_CHAT_MESSAGE";
